# Name of this GitHub Actions workflow.
name: Check-Semgrep

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep:1.109.0
    continue-on-error: true
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
